### ISSUE TITLE
double space in disassambler.py split call

### ISSUE THREAD

**Issue by raznor** [Dynetics/Malfunction#1]
flist.append(line.decode("utf-8").split("  ")) contains a double space. leads to not splitting the string.

**Comment by JeramyLochner** [comment]
What version of Radare2 are you using? There might be some disconnect between versions and how it outputs what we're looking for. If I run the command that Malfunction is parsing output from I get something like:

0x004048c5&nbsp; 42&nbsp; 1&nbsp; entry0
0x004024f0&nbsp; 6&nbsp; 1&nbsp; sym.imp.__libc_start_main
etc
etc

Different versions of Radare2 might output that command differently and we might need to start accounting for that though.

**Comment by raznor** [comment]
Ah, yes. Sorry might be my fault, I did use the radare from the ubuntu repository.

radare2 0.9.6 @ linux-little-x86-64 git.0.9.6
commit: 1: build: 2014-04-10

May I suggest to use .split() without parameter. This should fix it and produces the correct output with any number of whitespaces.

str_input = "0x645453  64      lalalala lololol             this_is_a_cookie"
flist=[]
flist = str_input.decode("utf-8").split();
for item in flist:
        if " " in item:
                print("lol try again")
        else:
                print (item)

**Comment by JeramyLochner** [comment]
Ah yeah that'd work fine. Appreciate it, hadn't done a ton of testing with different versions of Radare2
